<?php

namespace Componenta\Http\Middleware\Adapter;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;

final class RequestHandlerAdapter implements MiddlewareInterface, RequestHandlerInterface
{
    /**
     * Request attribute key for storing the fallback handler.
     *
     * This constant defines the attribute key used to inject the next handler
     * in the middleware pipeline into the request object. The wrapped handler
     * can access this fallback handler if needed for conditional processing
     * or advanced middleware patterns.
     *
     * The key uses a fully-qualified namespace to avoid conflicts with
     * application-specific attributes and provides clear identification
     * of the adapter's internal functionality.
     */
    public const string FALLBACK_HANDLER_ATTRIBUTES_KEY = "Componenta\Http\Middleware\Adapter:fallback";

    /**
     * Creates a new request handler adapter.
     *
     * @param RequestHandlerInterface $handler The request handler to wrap.
     *                                         This handler will be called for both
     *                                         middleware processing and direct handling.
     */
    public function __construct(
        private readonly RequestHandlerInterface $handler,
    ) {
    }

    /**
     * Processes a server request as middleware by delegating to the wrapped handler.
     *
     * This method implements the MiddlewareInterface by:
     * 1. Injecting the fallback handler into the request attributes
     * 2. Delegating request processing to the wrapped handler
     * 3. Returning the handler's response directly
     *
     * The fallback handler injection allows the wrapped handler to access
     * the next handler in the pipeline through request attributes if needed.
     * This enables advanced scenarios where the handler needs to conditionally
     * delegate to the next middleware in the chain.
     *
     * @param ServerRequestInterface $request The server request to process
     * @param RequestHandlerInterface $handler The next handler in the middleware pipeline
     * @return ResponseInterface The response generated by the wrapped handler
     *
     * @example Handler accessing fallback
     * ```php
     * class ConditionalHandler implements RequestHandlerInterface
     * {
     *     public function handle(ServerRequestInterface $request): ResponseInterface
     *     {
     *         if ($this->shouldDelegate($request)) {
     *             $fallback = $request->getAttribute(RequestHandlerAdapter::FALLBACK_HANDLER_ATTRIBUTES_KEY);
     *             return $fallback->handle($request);
     *         }
     *         return $this->generateResponse($request);
     *     }
     * }
     * ```
     */
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        return $this->handler->handle(
            $request->withAttribute(self::FALLBACK_HANDLER_ATTRIBUTES_KEY, $handler)
        );
    }

    /**
     * Handles a server request directly by delegating to the wrapped handler.
     *
     * This method implements the RequestHandlerInterface by directly
     * delegating to the wrapped handler without any modifications.
     * It enables the adapter to function as a standalone request handler
     * when not used within a middleware pipeline.
     *
     * No fallback handler is injected in this case since there is no
     * middleware pipeline context to provide one.
     *
     * @param ServerRequestInterface $request The server request to handle
     * @return ResponseInterface The response generated by the wrapped handler
     *
     * @example Direct handler usage
     * ```php
     * $adapter = new RequestHandlerAdapter($handler);
     * $response = $adapter->handle($request);
     * // Equivalent to: $handler->handle($request)
     * ```
     */
    public function handle(ServerRequestInterface $request): ResponseInterface
    {
        return $this->handler->handle($request);
    }
}